language: php

cache:
  directories:
    - $HOME/.composer/cache/files

sudo: false

php:
  - 7.4
  - 8.0

before_install:
    - composer self-update

install:
    - composer require "php-http/guzzle6-adapter:^2.0" --no-update
    - composer --prefer-source install

notifications:
  email:
    - i.rakovets@artox.com
